[package]
name = "SeaPad"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "dev" }

[addresses]
seapad =  "0x00"
sui =  "0x02"


# staking admin
treasury_admin = "0x98a890e3a370a3e4005460bfcd31dd4adf0f36af6d760bfd2c7014ac6ee2b17e"
stake_emergency_admin = "0x98a890e3a370a3e4005460bfcd31dd4adf0f36af6d760bfd2c7014ac6ee2b17e"

# staking test addresses.
treasury = "0x13"
emergency = "0x14"
alice = "0x15"
bob = "0x16"