rpc =  "https://fullnode.testnet.sui.io"
faucet =  "https://faucet.testnet.sui.io/gas"
###Seapad
Admin=0x154c6c6b4408ed15267eec15a35b97741287b973d23ed9e08528ec276008e6d6
VersionId=0x13a9e1b4369dd8f3fdb023d57d0115ca8623ddfcf7dcff31a80faee59f0f53a0
VersionAdmin=0xf86be321275975e9f329428d6d431a6b9246d2c92ca508934e9f4be648d5aebc
PackageID=0xa199c62ed91d99586c43689f22eed7c264fb4e2987a7cbcc0bd69573aed0b9dd

###Stake
StakeConfig=0x0665f513481c6112028b5a0668cec0b46facc93822e00e7329e9c4db4d8da018
PackageId=0xa52e9e04c9c6d900430168a472e53e6ff05a70c647f32e50e66b52cdfe3783dd

###Token
SPT=0x4996d20c1961272f97a80f0acd379e4a82b3109dd24c57b6be6a9afa9bbf6543
USDT=0xe2fb812e823d6806f86136517171b4fb91624dc99777d3e6e7ea974394a0840d
PackageID=0x2b1584a5ddf5351ec7742e51bd7ac0ca4dee9f31cd1e568c506503e1a5b7a29f

###Kyc&Referal
KycAdmin=0xbd5a0ffc5203e55774aa7f76a8c5c67641867e08b8c80699838826f58725e340
Kyc=0x9f639d302f918f160e0ce2546a3eeaba6803d40ecaca2b644cc14bbe7b30df93
ReferalAdmin=0xa9c6e5a9cd5bc7f74154c50d7a71663b82e520ba2d59bd8a63ae2fa905b8c814
CommonPackage=0x3dabe513e3c35f15475e73b839dde6bfe4ec3a7abe56bd02a0268464f58d0f28

###Nft
Nftadmin=0x5d31b8ec74d72c8c944cb507f5c0206ab94b433c5eecb45e1e0b7d909ccbc7eb
NftBox=0xf196875cd06392f0035ba5361a7786bd9aa1bcd7a414be56eff0471346f148c8
NftpackageId=0xc1336b67ea7a966910d875bb69d9b4e00e6440336491f34fff0aac7916abb5a1