[package]
name = "SeaPad"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
seapad =  "0x00"
sui =  "0x02"


# staking admin
treasury_admin = "0x01a7e3c7a16c9c4caa61941ccb30a336dc38673e0ee6cd19491ff71415eea869"
stake_emergency_admin = "0x01a7e3c7a16c9c4caa61941ccb30a336dc38673e0ee6cd19491ff71415eea869"

# staking test addresses.
treasury = "0x13"
emergency = "0x14"
alice = "0x15"
bob = "0x16"